version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: precaju-postgres
    environment:
      POSTGRES_DB: precaju
      POSTGRES_USER: precaju
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U precaju -d precaju"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - precaju-network

  redis:
    image: redis:7-alpine
    container_name: precaju-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - precaju-network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: precaju-backend
    expose:
      - "8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/precaju
      SPRING_DATASOURCE_USERNAME: precaju
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - backend_uploads:/app/uploads
    networks:
      - precaju-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: precaju-frontend
    expose:
      - "3000"
    environment:
      VITE_API_URL: http://localhost/api/v1
      VITE_WS_URL: ws://localhost/ws
    depends_on:
      backend:
        condition: service_healthy
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    networks:
      - precaju-network

  nginx:
    image: nginx:alpine
    container_name: precaju-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - nginx_logs:/var/log/nginx
    depends_on:
      - frontend
      - backend
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - precaju-network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  backend_uploads:
    driver: local
  nginx_logs:
    driver: local

networks:
  precaju-network:
    driver: bridge



