version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: precaju-postgres
    environment:
      POSTGRES_DB: precaju
      POSTGRES_USER: precaju
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U precaju -d precaju"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_data:
    driver: local
