# Configuration pour le debug des requêtes SQL et POI
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        type: trace

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type: TRACE
    gw.precaju: DEBUG
    gw.precaju.repository.POIRepository: DEBUG
    gw.precaju.service.POIService: DEBUG
    gw.precaju.controller.POIController: DEBUG
    org.springframework.transaction: DEBUG
    org.springframework.orm.jpa: DEBUG
    org.springframework.data.jpa: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"


